name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: debug info
      run: |
        echo "Ref: ${{ github.ref }}"
        echo "Event: ${{ github.event_name }}"
    - run: npm ci
    
    - run: npm run lint
    
    - run: npm run build

    - run: npm test

  terraform-validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0
    
    - name: Terraform Format Check
      run: terraform fmt -check -recursive terraform/
    
    - name: Terraform Validate
      run: |
        for module in terraform/modules/*/; do
          echo "Validating $module"
          cd "$module"
          terraform init -backend=false
          terraform validate
          cd - > /dev/null
        done
  
  publish-cdk:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    needs: [test, terraform-validate]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    
    - name: Use Node.js from .nvmrc
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: npm
        registry-url: https://npm.pkg.github.com

    - run: npm ci
    
    - run: npm run build
    
    - run: |
        cd cdk
        # Check if this version already exists on GitHub Packages
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        if npm view @sds9-org/cdk@$CURRENT_VERSION --registry=https://npm.pkg.github.com 2>/dev/null; then
          echo "Version $CURRENT_VERSION already exists, skipping publish"
        else
          echo "Publishing version $CURRENT_VERSION to GitHub Packages"
          npm publish --registry=https://npm.pkg.github.com
        fi
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
